name: Remote SSH

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd www/crm-rbt.any-media.ru
          eval $(ssh-agent -s)
          ssh-add .ssh/personal_key
          (php artisan down) || true
          git pull
          sudo chmod -R 777 ./storage
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan clear-compiled
          php artisan optimize
          npm install
          npm run build
          php artisan route:clear
          php artisan cache:clear
          php artisan config:clear
          php artisan view:clear
          php artisan migrate --force
          php artisan up
          
